# -*- coding: utf-8 -*-
"""Apostila - 00. Índice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qH2RUurym6O-OGiHBgJp1bmMS8UNEjhx

#SOBRE A APOSTILA
  
O mundo tecnológico praticamente já não admite quem não saiba pelo menos um pouquinho de Python. As maiores demandas em linguagem de programação e os maiores retornos financeiros se concentram nos profissinais cujo conhecimento abrange essa linguagem. Além disso, ela é frequentemente ensinada em cursos de lógica, devido à simplicidade da sua sintaxe. Assim, para você que nunca teve contato com nenhuma linguagem de programação, está começando pelo lugar certo! Se não for o seu caso, e você já tiver alguma experiência com programação, tudo bem. Python vai te devolver toda aquela motivação pela área de *programming*. 

  As principais aplicações de Python se concentram em Inteligência Artificial e Aprendizado de Máquina (Machine Learning – ML), mas essa apostila tem o intuito de apresentar e desmistificar a sintaxe básica, além de explicar algumas intuições sobre a estrutura do programa em si. Contrastando com a literatura existente, o objetivo dos autores é explicar de forma simples, clara e interativa tudo o que você precisa saber para se garantir na linguagem. 
  
 Esta apostila está hospedada em dois "aplicativos" diferentes: um deles é o Colaboratory, hospedado pelo Drive do Google, que tem o intuito de facilitar e dinamizar o aprendizado. Com ele, é possível rodar o código e ver na prática Python acontecendo. O outro é o GitBook, que tem o formato de livro virtual e é legal para se situar dentro da apostila, além de ser ideal para impressão.

Com isso, esse material foi desenvolvido em 2018 pelos alunos Augusto Hochleitner, Maria Eduarda Furtado e Natália Zanoni, membros do PET Engenharia de Produção da UFSC, orientado pelo professor Ricardo Giglio, com dois principais intuitos: o curso de Python, parte do portfólio de cursos do PET, e a matéria de Informática para Engenharia de Produção da UFSC (EPS7001).

#ÍNDICE

**01. Introdução**
 *  Sobre o Colaboratory
 *   Programas de Python
 *   Objetos
 *   Objetos escalares
 *   Atribuindo valores às variáveis
 *   Conversões de tipo (cast)
 *    Expressões
 *    Abstraindo expressões
 *    Programação vs. matemática
 *    Trocando atribuições


**02. Condicionais**
*   Valores booleanos
*   `If`
*   `Else`
*   `Elif`

**03. Estrutura de Repetição - Loops**
*   Loops com `while` 
*   `Break`
*   Loops com `for`
*   `Range( )`
*   Nested loops

**04. Functions**
*   Sintaxe
*   `Help()`
*   Alguns detalhes sobre funções

**05. Strings**
*   Imutabilidade
*   Função `replace`

**06. Listas**
*   Acessando uma `list`
*   Funções reservadas para listas
*   Listas e strings
*   Mutabilidade


**07. Sequências**
*  Tuplas
*  Sequências

**08. Dicionários**
*  Criando um dicionário
*  Acessando elementos de um dicionário
*  Operadores em dicionários
*  Percorrendo dicionários com loops

**09. Introdução a objetos**
*  Explorando valores e referências
*  Explorando mutabilidade
*  Variáveis locais
*  Explorando o escopo

**10. Classes**
*  O que é um instância?
*  Criando uma `classe`
*  Usando `classes`
*  Subclases
*  Conceito de herança

**11. Generators**


**Apêndice 1: Matemática Simbólica**


**Apêndice 2: Gabarito Exercícios Apostilas**
"""